### ISSUE TITLE
sudo/root

### ISSUE THREAD

**Issue by straussmaus** [android-x86/android-x86.github.io#105]
Hi, first time trying Android.  I'm using today's version of the CM version 10.

Problem: I can't do anything.  I open a terminal and for some reason I don't have root access.

There is no `sudo` installed.

How do I do stuff please?  I'm assuming this is a bug but it's possible that there is another name for sudo in Android/CM?

**Comment by android-x86** [comment]
straussmaus <notifications@github.com> 於 2020年12月23日 週三 下午5:36寫道：

> Hi, first time trying Android. I'm using today's version of the CM version
> 10.
>
> Problem: I can't do anything. I open a terminal and for some reason I
> don't have root access.
>
> There is no sudo installed.
>
> How do I do stuff please? I'm assuming this is a bug but it's possible
> that there is another name for sudo in Android/CM?
>

su

**Comment by straussmaus** [comment]
HAHA!  Okay now I feel very stupid.  And also, thank you.

**Comment by straussmaus** [comment]
(Is there a user forum?  IRC with people in the room? I can try to ask me stupid questions there in the future.)
