### ISSUE TITLE
Website Not Loading - Showing Blank Page

### ISSUE THREAD

**Issue by p134c0d3** [android-x86/android-x86.github.io#127]
When trying to access [https://www.android-x86.org](https://www.android-x86.org) it redirects to [https://www.android-x86.org/lander](https://www.android-x86.org/lander) and just shows a blank page as notated below

![image](https://github.com/user-attachments/assets/0610d0d8-d495-475f-a8a5-2458778490bc)

**Comment by p134c0d3** [comment]
I tried across multiple browsers (Floorp, Chromium, Brave (with Shields OFF)), without any success, getting the same result across various browsers.

**Comment by TukangM** [comment]
thr domain is expired. GoDaddy claimed the domain it's self

**Comment by kinow** [comment]
Came to report the same. It's a blank page for me, unless I disable uBlock, then it shows the GoDaddy page :disappointed_relieved:

**Comment by gun-hash** [comment]
Redirecting me to the Godaddy page too

**Comment by Xtr126** [comment]
The domain is back again 🙂
![Screenshot_20240904_101912_Kiwi Browser](https://github.com/user-attachments/assets/efb5ce40-174b-4aad-b24c-5aafa1589b02)

**Comment by kinow** [comment]
Yup, appears to work fine for me.
