### ISSUE TITLE
Can't disable ForceDefaultOrientation

### ISSUE THREAD

**Issue by Matt1700** [android-x86/android-x86.github.io#74]
I installed Android x86 8.1-r1 on an AMD pc. I need to permanently rotate the screen to portrait mode (9:16) but the **ForceDefaultOrientation** feature of Android x86 forces every app to be in landscape mode. 

I tried changing the screen resolution to 1080x1920 with the `wm size` command but it doesn't help.

Is there a way to disable this feature?

**Comment by payam-mobilityone** [comment]
same problem here
