### ISSUE TITLE
BD PROCHOT cpu throttling (msr read and write)

### ISSUE THREAD

**Issue by imad07mos** [android-x86/android-x86.github.io#81]
Hello , lot of intel laptops suffers from BD PROCHOT flag that throttles cpu when charging , its easily fixable in windows using throttlestop and linux using msr tools

me and my friend tried to port msr tools to android x86 and compiled it using ndk in Android 7.x source

copied binary files and chmoded them then modprobe msr

rdmsr 0x1FC

it returns this error "rdmsr: open : no such file or directory"

here is the source code of what my friend compiled

https://github.com/hmtheboy154/msr-tools-android

reference :

https://github.com/DivyanshuVerma/throttlestop-linux

**Comment by android-x86** [comment]
imad07mos <notifications@github.com> 於 2020年4月12日 週日 下午11:17寫道：
>
> Hello , lot of intel laptops suffers from BD PROCHOT flag that throttles cpu when charging , its easily fixable in windows using throttlestop and linux using msr tools
>
> me and my friend tried to port msr tools to android x86 and compiled it using ndk in Android 7.x source
>
> copied binary files and chmoded them then modprobe msr
>
> rdmsr 0x1FC
>
> it returns this error "rdmsr: open : no such file or directory"
>
> here is the source code of what my friend compiled
>
> https://github.com/hmtheboy154/msr-tools-android

Thank you for the info.
Though I don't understand what the issue is.
Reading the code, the Android patch has a small bug:

   sprintf(msr_file_name, "/dev/cpu/msr%d", cpu);

It generates the error you saw. Should be

  sprintf(msr_file_name, "/dev/msr%d", cpu);

On the other hand, the wrmsr.c has the correct path.

> reference :
>
> https://github.com/DivyanshuVerma/throttlestop-linux


-- 
Chih-Wei
Android-x86 project
http://www.android-x86.org

**Comment by imad07mos** [comment]
> imad07mos <notifications@github.com> 於 2020年4月12日 週日 下午11:17寫道：
> Hello , lot of intel laptops suffers from BD PROCHOT flag that throttles cpu when charging , its easily fixable in windows using throttlestop and linux using msr tools me and my friend tried to port msr tools to android x86 and compiled it using ndk in Android 7.x source copied binary files and chmoded them then modprobe msr rdmsr 0x1FC it returns this error "rdmsr: open : no such file or directory" here is the source code of what my friend compiled https://github.com/hmtheboy154/msr-tools-android
> Thank you for the info. Though I don't understand what the issue is. Reading the code, the Android patch has a small bug: sprintf(msr_file_name, "/dev/cpu/msr%d", cpu); It generates the error you saw. Should be sprintf(msr_file_name, "/dev/msr%d", cpu); On the other hand, the wrmsr.c has the correct path.
> […](#)
> reference : https://github.com/DivyanshuVerma/throttlestop-linux
> -- Chih-Wei Android-x86 project http://www.android-x86.org

thank you very much , i didnt notice the path error in rdmsr 
recompiled  and its working 
no more cpu throttling :)

**Comment by imad07mos** [comment]
reopened it to mark it as solved
